export const BANK_LIST = [
  { value: '', label: 'Không chọn' },
  { value: 'VNPAYQR', label: 'Ngân hàng VNPAYQR' },
  { value: 'NCB', label: 'Ngân hàng NCB' },
  { value: 'SCB', label: 'Ngân hàng SCB' },
  { value: 'SACOMBANK', label: 'Ngân hàng SACOMBANK' },
  { value: 'EXIMBANK', label: 'Ngân hàng EXIMBANK' },
  { value: 'MSBANK', label: 'Ngân hàng MSBANK' },
  { value: 'NAMABANK', label: 'Ngân hàng NAMABANK' },
  { value: 'VISA', label: 'Ngân hàng VISA' },
  { value: 'VNMART', label: 'Ngân hàng VNMART' },
  { value: 'VIETINBANK', label: 'Ngân hàng VIETINBANK' },
  { value: 'VIETCOMBANK', label: 'Ngân hàng VIETCOMBANK' },
  { value: 'HDBANK', label: 'Ngân hàng HDBANK' },
  { value: 'DONGABANK', label: 'Ngân hàng Dong A' },
  { value: 'TPBANK', label: 'Ngân hàng Tp Bank' },
  { value: 'OJB', label: 'Ngân hàng OceanBank' },
  { value: 'BIDV', label: 'Ngân hàng BIDV' },
  { value: 'TECHCOMBANK', label: 'Ngân hàng Techcombank' },
  { value: 'VPBANK', label: 'Ngân hàng VPBank' },
  { value: 'AGRIBANK', label: 'Ngân hàng AGRIBANK' },
  { value: 'MBBANK', label: 'Ngân hàng MBBank' },
  { value: 'ACB', label: 'Ngân hàng ACB' },
  { value: 'OCB', label: 'Ngân hàng OCB' },
  { value: 'SHB', label: 'Ngân hàng SHB' },
  { value: 'IVB', label: 'Ngân hàng IVB' },
];
