const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  PHONE_SIGN_IN_START: 'PHONE_SIGN_IN_START',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SET_USER_PHONE_NUMBER: 'SET_USER_PHONE_NUMBER',
  SEND_PHONE_VERIFICATION: 'SEND_PHONE_VERIFICATION',
  VERIFY_PHONE: "VERIFY_PHONE",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_NAME_AND_IMAGE: "SET_NAME_AND_IMAGE",
  SET_EMAIL: "SET_EMAIL",
  SET_PHONE_NUMBER: "SET_PHONE_NUMBER",
  VERIFY_EMAIL: "SET_PHONE_NUMBER",
  UPDATE_STORED_USER: "UPDATE_STORED_USER",
  SET_REGISTER_INFO: "SET_REGISTER_INFO"
};

export default UserActionTypes;
