export const categoryIconMapper = {
  201: {
    id: '201',
    name: 'Đồ cổ, đồ thủ công, hàng sưu tầm',
    englishName: 'Antiques, collectibles, Arts & Craft',
    description: '',
    iconSrc: '/assets/categories/stamp.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  202: {
    id: '202',
    name: 'Mẹ và bé',
    englishName: 'Mom & Baby',
    description: '',
    iconSrc: '/assets/categories/mom-baby.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  203: {
    id: '203',
    name: 'Ăn uống, thực phẩm',
    englishName: 'Food & beverages, supplies',
    description: '',
    iconSrc: '/assets/categories/food.svg',
    fill: 'none',
    stroke: '#0D1B1E',
  },
  204: {
    id: '204',
    name: 'Sách và sách điện tử',
    englishName: 'Books & eBooks',
    description: '',
    iconSrc: '/assets/categories/book.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  205: {
    id: '205',
    name: 'Văn phòng',
    englishName: 'Office equipment & supplies',
    description: '',
    iconSrc: '/assets/categories/printer.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  206: {
    id: '206',
    name: 'Đồ điện tử',
    englishName: 'Digitals',
    description: '',
    iconSrc: '/assets/categories/monitor.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  207: {
    id: '207',
    name: 'Gia dụng',
    englishName: 'Home depot',
    description: '',
    iconSrc: '/assets/categories/vacuum-cleaner.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  208: {
    id: '208',
    name: 'Thời trang',
    englishName: 'Clothes & accessories',
    description: '',
    iconSrc: '/assets/categories/t-shirt.svg',
    fill: 'none',
    stroke: '#0D1B1E',
  },
  209: {
    id: '209',
    name: 'Mỹ phẩm và nước hoa',
    englishName: 'Cosmetics & Fragrances',
    description: '',
    iconSrc: '/assets/categories/lipstick.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  210: {
    id: '210',
    name: 'Nội thất và trang trí',
    englishName: 'Furniture & decor',
    description: '',
    iconSrc: '/assets/categories/furnitures.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  211: {
    id: '211',
    name: 'Thiết bị thể thao',
    englishName: 'Exercise & fitness',
    description: '',
    iconSrc: '/assets/categories/muscle.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  212: {
    id: '212',
    name: 'Thiết bị, vật tư công nghiệp',
    englishName: 'Industrial equipment & Supplies',
    description: '',
    iconSrc: '/assets/categories/driller.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  213: {
    id: '213',
    name: 'Y tế và sức khỏe',
    englishName: 'Medical & health',
    description: '',
    iconSrc: '/assets/categories/bandage.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  214: {
    id: '214',
    name: 'Giải trí',
    englishName: 'Entertainments',
    description: '',
    iconSrc: '/assets/categories/media.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  215: {
    id: '215',
    name: 'Phần mềm, sản phẩm điện tử',
    englishName: 'Software',
    description: '',
    iconSrc: '/assets/categories/software.svg',
    fill: '#0D1B1E',
    stroke: 'none',
  },
  216: {
    id: '216',
    name: 'Ô tô xe máy',
    englishName: 'Vehicles & parts',
    description: '',
    iconSrc: '/assets/categories/car.svg',
    fill: 'none',
    stroke: '#0D1B1E',
  },
  217: {
    id: '217',
    name: 'Thú cưng',
    englishName: 'Pet supplies',
    description: '',
    iconSrc: '/assets/categories/pet.svg',
    fill: 'none',
    stroke: '#0D1B1E',
  },
  218: {
    id: '218',
    name: 'Ngoài trời và du lịch',
    englishName: 'Outdoor & travel',
    description: '',
    iconSrc: '/assets/categories/luggage.svg',
    fill: 'none',
    stroke: '#0D1B1E',
  },
  299: {
    id: '299',
    name: 'Khác',
    englishName: 'Other',
    description: '',
    iconSrc: '/assets/categories/box.svg',
    fill: 'none',
    stroke: '#0D1B1E',
  },
};
