export const categoryIconMapper = {
  201: {
    id: '201',
    name: 'Điện tử',
    englishName: 'Electronics',
    description: '',
    iconSrc: '/assets/categories/monitor.svg',
  },
  202: {
    id: '202',
    name: 'Thời trang & phụ kiện',
    englishName: 'Fashion & Accessories',
    description: '',
    iconSrc: '/assets/categories/t-shirt.svg',
  },
  203: {
    id: '203',
    name: 'Nhà cửa & đời sống',
    englishName: 'Home, Kitchen & Garden',
    description: '',
    iconSrc: '/assets/categories/vacuum-cleaner.svg',
  },
  204: {
    id: '204',
    name: 'Ô tô, xe máy & linh kiện',
    englishName: 'Automotive & Accessories',
    description: '',
    iconSrc: '/assets/categories/car.svg',
  },
  205: {
    id: '205',
    name: 'Sách, Điện ảnh & Âm nhạc (Giải trí)',
    englishName: 'Books, Movies & Music (Entertainment)',
    description: '',
    iconSrc: '/assets/categories/media.svg',
  },
  206: {
    id: '206',
    name: 'Thú cưng',
    englishName: 'Pet',
    description: '',
    iconSrc: '/assets/categories/pet.svg',
  },
  207: {
    id: '207',
    name: 'Sưu tầm & nghệ thuật',
    englishName: 'Collectibles & Art',
    description: '',
    iconSrc: '/assets/categories/stamp.svg',
  },
  208: {
    id: '208',
    name: 'Đồ chơi & Games',
    englishName: 'Toys & Games',
    description: '',
  },
  209: {
    id: '209',
    name: 'Thương mại & Công nghệ',
    englishName: 'Business & Industrial',
    description: '',
  },
  210: {
    id: '210',
    name: 'Sức khỏe & Sắc đẹp',
    englishName: 'Health & Beauty',
    description: '',
    iconSrc: '/assets/categories/bandage.svg',
  },
  211: {
    id: '211',
    name: 'Thể thao',
    englishName: 'Sporting Goods',
    description: '',
    iconSrc: '/assets/categories/muscle.svg',
  },
  212: {
    id: '212',
    name: 'Du lịch',
    englishName: 'Travel',
    description: '',
    iconSrc: '/assets/categories/luggage.svg',
  },
  299: {
    id: '299',
    name: 'Khác',
    englishName: 'Other',
    description: '',
    iconSrc: '/assets/categories/box.svg',
  },
};
